trying configuring with --host=x86_64-w64-mingw32
fails in bfd with:
libbfd.h:300:46: error: initialization of ‘int (*)(bfd *, struct stat *)’ from incompatible pointer type ‘int (*)(bfd *, struct _stat64 *)’ [-Wincompatible-pointer-types]
  300 | #define _bfd_noarchive_generic_stat_arch_elt bfd_generic_stat_arch_elt
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
bfd.h:6838:3: note: in expansion of macro ‘_bfd_noarchive_generic_stat_arch_elt’
 6838 |   NAME##_generic_stat_arch_elt, \
      |   ^~~~
srec.c:1266:3: note: in expansion of macro ‘BFD_JUMP_TABLE_ARCHIVE’
 1266 |   BFD_JUMP_TABLE_ARCHIVE (_bfd_noarchive),
      |   ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[3]: *** [libbfd_a-srec.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-bfd] Error 2

Change-Id: I1d626feb871ffb3b75be11e2d09068df60ff4d21